### ISSUE TITLE
Bug: uploading files larger than 1GB                                      

### ISSUE THREAD

**Issue by semtisem** [unbekanntes-pferd/dco3#12]
**Description**
When uploading a file larger than 1GB thread panics.

**Error Message**
> [00:04:45] [=======================================>] 1020.00 MiB/1.00 GiB (3.68 MiB/s) Uploading                                                                   thread 'main' panicked at 'attempt to multiply with overflow', ../.cargo/registry/src/index.crates.io-6f17d22bba15001f/dco3-0.4.1/src/nodes/upload.rs:379:37

**Link to code line**
https://github.com/unbekanntes-pferd/dco3/blob/2ff39127306bd0b6a508d0b2dbacc289c68091de/src/nodes/upload.rs#L391C1-L391C83 

PS: 
Please add labels ;)

**Comment by unbekanntes-pferd** [comment]
@semtisem thanks - issue should be fixed with https://github.com/unbekanntes-pferd/dco3/pull/13
I'm not sure what the issue with labels is though - they are available, but you cannot set them, not being a maintainer.
